import { MigrationInterface, QueryRunner } from 'typeorm';

export class mockpost1616188539471 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into post (title, text, "creatorID", "createdAt") values ('Sebring', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 2, '2020-04-24T05:33:16Z');
insert into post (title, text, "creatorID", "createdAt") values ('MDX', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 2, '2021-02-16T03:45:53Z');
insert into post (title, text, "creatorID", "createdAt") values ('Corolla', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 2, '2019-12-29T03:30:35Z');
insert into post (title, text, "creatorID", "createdAt") values ('Ram 3500', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 2, '2020-02-13T13:18:13Z');
insert into post (title, text, "creatorID", "createdAt") values ('Regal', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 2, '2021-02-11T13:19:12Z');
insert into post (title, text, "creatorID", "createdAt") values ('98', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 2, '2020-10-30T04:23:01Z');
insert into post (title, text, "creatorID", "createdAt") values ('S80', 'Fusce consequat. Nulla nisl. Nunc nisl.', 2, '2021-01-11T19:26:47Z');
insert into post (title, text, "creatorID", "createdAt") values ('Challenger', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 2, '2020-05-25T08:05:24Z');
insert into post (title, text, "creatorID", "createdAt") values ('Chariot', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 2, '2021-02-23T06:28:18Z');
insert into post (title, text, "creatorID", "createdAt") values ('Intrepid', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 2, '2020-06-24T15:49:00Z');
insert into post (title, text, "creatorID", "createdAt") values ('RAV4', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 2, '2020-03-10T08:52:01Z');
insert into post (title, text, "creatorID", "createdAt") values ('Bronco', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2, '2020-10-19T09:58:40Z');
insert into post (title, text, "creatorID", "createdAt") values ('Range Rover', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 2, '2020-02-18T21:02:45Z');
insert into post (title, text, "creatorID", "createdAt") values ('Wrangler', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2, '2020-12-02T12:36:14Z');
insert into post (title, text, "creatorID", "createdAt") values ('Tahoe', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 2, '2020-04-01T14:33:19Z');
insert into post (title, text, "creatorID", "createdAt") values ('Sportvan G20', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 2, '2020-10-11T18:14:59Z');
insert into post (title, text, "creatorID", "createdAt") values ('300', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 2, '2020-04-13T17:53:44Z');
insert into post (title, text, "creatorID", "createdAt") values ('Express 2500', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 2, '2021-01-18T22:46:04Z');
insert into post (title, text, "creatorID", "createdAt") values ('600', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2, '2021-02-03T19:48:11Z');
insert into post (title, text, "creatorID", "createdAt") values ('Miata MX-5', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 2, '2020-12-18T09:27:31Z');
insert into post (title, text, "creatorID", "createdAt") values ('Golf', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 2, '2020-10-20T19:37:18Z');
insert into post (title, text, "creatorID", "createdAt") values ('PT Cruiser', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 2, '2020-11-30T14:03:02Z');
insert into post (title, text, "creatorID", "createdAt") values ('Cube', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 2, '2020-01-15T00:32:38Z');
insert into post (title, text, "creatorID", "createdAt") values ('Aventador', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 2, '2021-01-22T17:04:55Z');
insert into post (title, text, "creatorID", "createdAt") values ('Envoy XUV', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 2, '2021-01-16T09:19:57Z');
insert into post (title, text, "creatorID", "createdAt") values ('Firefly', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2, '2020-03-04T17:25:48Z');
insert into post (title, text, "creatorID", "createdAt") values ('Phaeton', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 2, '2020-06-30T22:14:43Z');
insert into post (title, text, "creatorID", "createdAt") values ('300ZX', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 2, '2021-01-28T04:01:54Z');
insert into post (title, text, "creatorID", "createdAt") values ('Z3', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 2, '2020-07-11T01:16:38Z');
insert into post (title, text, "creatorID", "createdAt") values ('911', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2, '2020-07-31T21:24:17Z');
insert into post (title, text, "creatorID", "createdAt") values ('924 S', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 2, '2021-01-08T13:21:04Z');
insert into post (title, text, "creatorID", "createdAt") values ('GTO', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 2, '2020-05-08T04:30:31Z');
insert into post (title, text, "creatorID", "createdAt") values ('E-Series', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 2, '2019-12-01T08:51:13Z');
insert into post (title, text, "creatorID", "createdAt") values ('911', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2, '2021-03-12T12:22:20Z');
insert into post (title, text, "creatorID", "createdAt") values ('Pilot', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2, '2020-06-28T09:54:16Z');
insert into post (title, text, "creatorID", "createdAt") values ('Mountaineer', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 2, '2020-06-16T03:55:12Z');
insert into post (title, text, "creatorID", "createdAt") values ('Cutlass Supreme', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 2, '2020-08-23T17:18:16Z');
insert into post (title, text, "creatorID", "createdAt") values ('GTI', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 2, '2020-05-20T04:58:47Z');
insert into post (title, text, "creatorID", "createdAt") values ('300ZX', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 2, '2020-06-05T13:31:11Z');
insert into post (title, text, "creatorID", "createdAt") values ('A6', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2, '2020-10-24T13:43:15Z');
insert into post (title, text, "creatorID", "createdAt") values ('Defender 90', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 2, '2020-01-16T15:03:52Z');
insert into post (title, text, "creatorID", "createdAt") values ('LHS', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2, '2020-04-22T16:58:55Z');
insert into post (title, text, "creatorID", "createdAt") values ('Armada', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2, '2020-03-05T10:15:08Z');
insert into post (title, text, "creatorID", "createdAt") values ('A4', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2, '2020-06-24T08:51:08Z');
insert into post (title, text, "creatorID", "createdAt") values ('Z4', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 2, '2021-01-03T06:07:10Z');
insert into post (title, text, "creatorID", "createdAt") values ('F-Series', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 2, '2021-02-01T09:52:14Z');
insert into post (title, text, "creatorID", "createdAt") values ('Lancer', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 2, '2021-01-31T07:09:17Z');
insert into post (title, text, "creatorID", "createdAt") values ('Durango', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 2, '2020-11-27T19:02:29Z');
insert into post (title, text, "creatorID", "createdAt") values ('Ram 1500 Club', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 2, '2020-07-13T15:35:02Z');
insert into post (title, text, "creatorID", "createdAt") values ('Prius', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 2, '2020-10-30T12:15:46Z');`);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
